- name: VPC destroyplaybook
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars/vpc_vars.yml

  tasks:
  - name: remove a VPC
    ec2_vpc_net:
      region: "{{ region }}"
      name: "{{ project_name }}"
      cidr_block: "{{ cidr_block }}"
      state: absent
    register: vpc
